### ISSUE TITLE
Error in exrex.count

### ISSUE THREAD

**Issue by s-tikhomirov** [asciimoo/exrex#14]
I observe the following behavior, and it is obviously incorrect:

`>>> list(exrex.generate("a|ab"))`
`[u'a', u'ab']`
`>>> exrex.count("a|ab")`
`1`

**Comment by asciimoo** [comment]
thanks, that's definitely a bug, i'll check it

**Comment by ao2** [comment]
Hi, I too saw this behavior when using alternatives: `'(foo|bar)(20|)16'`
