### ISSUE TITLE
Consider license change?

### ISSUE THREAD

**Issue by evilchili** [asciimoo/exrex#16]
Hello!

I would very much like to use this package, but I am prevented by doing so due to it being licensed under AGPL. Would you consider switching to LGPL, BSD, or CC licensing?

**Comment by arpit1997** [comment]
LOL :smile: @evilchili 
AGPL does not bound you not to use the package for most of the things it is greatly flexible.

> exrex is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

here it clearly  states that you can redistrbute it so do whatever you want.
and what is the special thing that you want to use this package for. :smile_cat:

**Comment by graingert** [comment]
@evilchili This project intentionally does not support proprietary software: https://github.com/asciimoo/exrex/issues/15#issuecomment-230768806

consider (rst.xeger)[https://bitbucket.org/leapfrogdevelopment/rstr/src#rst-header-xeger]
