### ISSUE TITLE
limit flag on generate() vs getone()

### ISSUE THREAD

**Issue by jlin83** [asciimoo/exrex#19]
Maybe I don't quite understand the limit flag on the two methods, generate() and getone().  I would expect that the limit flag is used to cap any substitution performed.  

```
# 41 is two characters long, I wanted a cap of 1
>>> exrex.getone(r'^(detail|test)/(?P<pk>\d+)/$', limit=1)
'test/41/'
# this seems to be okay using the generator
>>> g = exrex.generate(r'^(detail|test)/(?P<pk>\d+)/$', limit=1)
>>> while True:
...   next(g)
... 
'detail/0/'
'detail/1/'
'detail/2/'
'detail/3/'
'detail/4/'
'detail/5/'
'detail/6/'
'detail/7/'
'detail/8/'
'detail/9/'
'test/0/'
'test/1/'
'test/2/'
'test/3/'
'test/4/'
'test/5/'
'test/6/'
'test/7/'
'test/8/'
'test/9/'
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
StopIteration
>>> 

```

Is this a bug or am I misunderstanding the module usage?

**Comment by asciimoo** [comment]
@jlin83 `limit` limits the length of the infinite parts of the regular expression like `.+` or `[a-z]*` and not the number of generated strings. As you can see in your example, the `\d+` part produced only one digit numbers because of `limit=1`.

**Comment by jlin83** [comment]
Gotcha -that's what I assumed - and that's what's happening in the generate() example, right?  I'm still not understanding why the first example with getone() produced the string "41" when I chose limit=1.  Does it work differently for getone()?

**Comment by asciimoo** [comment]
It was an off-by-one bug, thanks!
