### ISSUE TITLE
some wrong with using exrex

### ISSUE THREAD

**Issue by heascle** [asciimoo/exrex#25]
I can't use 'exrex' neither in windows nor in debian.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "exrex.py", line 2, in <module>
    from exrex import exrex
ImportError: cannot import name exrex

I have try all the ways to install exrex,but it not work.
easy_install / pip install /pip2/    or  python setup.py install

help me.thanks.

**Comment by asciimoo** [comment]
Hello, it works well for me using pip. What is your python version?

**Comment by heascle** [comment]
root@kalivmware:~/mineprogramer/dic_builder.py# python3 exrex.py

1. Traceback (most recent call last):
2.   File "exrex.py", line 2, in <module>
3.     import exrex
4.   File "/root/mineprogramer/dic_builder.py/exrex.py", line 27, in <module>
5.     dic_create(host_para('http://demo.webdic.com/'))	
6.   File "/root/mineprogramer/dic_builder.py/exrex.py", line 23, in dic_create
7.     dics = list(exrex.generate(web_dic+'[!@#]'+dic_pass))
8. ## AttributeError: module 'exrex' has no attribute 'generate'

My python3 version is  " Python 3.5.3+"

**Comment by asciimoo** [comment]
Seems your own module is also called `exrex.py`. Rename it and probably the problem will be solved.

**Comment by heascle** [comment]
It works ! 

Thank you very much!
