### ISSUE TITLE
Allow input of capture groups

### ISSUE THREAD

**Issue by TMiguelT** [asciimoo/exrex#29]
I'm interested in being able to generate strings from a regular expression, but also with known values of the capture groups. For example, if we had the regex `First Name: (\w+), Last Name: (\w+)`, and known values of `John`, and `Smith`, I'd want it to use these values instead of generating them, resulting in a string like  `First Name: John, Last Name: Smith`. The API would be something like `getone(some_regex: str, known_values: list)`

Is this within the scope of this project?

**Comment by asciimoo** [comment]
@TMiguelT you can create a regular expression which acts as you described:
```python
import re
import exrex
name_regex = 'First Name: ({0}), Last Name: ({1})'.format(
    '|'.join(map(re.escape, ['John', 'Jane'])),
    '|'.join(map(re.escape, ['Smith', 'Doe'])),
)
print(exrex.getone(name_regex))
```

**Comment by TMiguelT** [comment]
That only works if I'm choosing from a limited number of options, which I'm not. Let's say every name in the world is an option, so the only way to express it is with `\w+` or similar. Then there needs to be actual logic to insert the capture group in. I'd be happy to write this feature if it makes sense.

**Comment by asciimoo** [comment]
> Let's say every name in the world is an option, so the only way to express it is with \w+ or similar.

How can you use every name in the world without collecting them? `\w+` can generate invalid names. If you have a list of names then the above solution works, otherwise you can use any regex e.g. `[A-Z][a-z]{3,6}`.
