### ISSUE TITLE
getting REGEX pattern from text file content

### ISSUE THREAD

**Issue by zdilto** [asciimoo/exrex#57]
after using exrex for months now, i finally stuck in a problem where i really **need** to get REGEX pattern from a file instead of the normal method: `exrex.py "[a-z][0-9]{0,2}"`
  
getting REGEX patterns from a text file line by line without the need to start new instance of exrex .

example:

patternfile.txt contents:
    [a-z][0-9]{0,2}
    [a-z][A-Z][a-z]{7}
    myName[0-9]{4}

one run code:
`
exrex.py patternfile.txt
`

 output:
a
a0
a00
......
s59
b7
......
aAv4621397
......
myName1980
.......

hope exrex will be updated very soon with this feature and other user suggested ones<br>
we really rely and this software and this method to complete our work

**Comment by sebix** [comment]
You can use basic shell features:
```bash
while read line; do exrex.py "$line"; done < patternfile.txt
```

**Comment by zdilto** [comment]
i'm using windows so i tested powershell and cmd still didn't test this in bash yet (may work)
in my case this will start new instances of exrex  and the exe for each line

`for /f "tokens=*" %G in ('type patternfile.txt') do (exrex "%~G")|exe params  `

i have to take a pic whenever exe exits,while starting new instances for each line
the result is a folder full of picture files and it is very tiring to check manually pic by pic if operation succeed knowing that exe don't return a success error code on exit.

i think is more flexible to let exrex do it without any hassle.

**Comment by sebix** [comment]
You won't reach your goal without a tiny programming effort.

**Comment by zdilto** [comment]
i followed your advice and you were right some tiny effort did the job
```

#add this in  argparser() function
   
  argp.add_argument(
             '-f', '--rexfile',
             help='get regular expression pattern from file',
             metavar='REGEX',
            default=False,
            type=argparse.FileType('r', encoding='utf-8')
    )

#add this in  __main__ function  try block

    if (args['regex'] == "" and args['rexfile'] != ""):
            for line in args['rexfile'].readlines():
                g = generate(line, args['limit'])
    elif(args['regex'] != ""):
            g = generate(args['regex'], args['limit'])
    
```

**Comment by rautamiekka** [comment]
> `for /f "tokens=*" %G in ('type patternfile.txt') do (exrex "%~G")|exe params `

There's only 1 method to start a single instance: creating a concatenated string from the params. Every single other (that I know of) starts a new instance.

Pretty sure there's a command for screenshots like on Linux, even if you need to install another app.

**Comment by zdilto** [comment]
> 
> ```
> 
> #add this in  argparser() function
>    
>   argp.add_argument(
>              '-f', '--rexfile',
>              help='get regular expression pattern from file',
>              metavar='REGEX',
>             default=False,
>             type=argparse.FileType('r', encoding='utf-8')
>     )
> 
> #add this in  __main__ function  try block
> 
>     if (args['regex'] == "" and args['rexfile'] != ""):
>             for line in args['rexfile'].readlines():
>                 g = generate(line, args['limit'])
>     elif(args['regex'] != ""):
>             g = generate(args['regex'], args['limit'])
>     
> ```

after testing and testing again i noticed that **only the last line is generated** from the patternfile.txt,don't understand why
please help

**Comment by zdilto** [comment]
work successfully

```
if (args['regex'] == "" and args['rexfile'] != ""):
        for line in args['rexfile'].readlines():
            try:
                g = generate(line.rstrip(), args['limit'])
            except Exception as e:
                args['rexfile'].close()
                stderr.write('[!] Error: %s\n' % e)
                exit(1)
            args['output'].write(next(g))
            args['max_number'] -= 1
            for s in g:
                if args['max_number'] == 0:
                    break
                args['max_number'] -= 1
                args['output'].write(args['delimiter'])
                args['output'].write(s)
            if args['delimiter'] == '\n':
                args['output'].write('\n')
        args['rexfile'].close()
    elif(args['regex'] != ""):
        try:
            g = generate(args['regex'], args['limit'])
        except Exception as e:
            stderr.write('[!] Error: %s\n' % e)
            exit(1)
        args['output'].write(next(g))
        args['max_number'] -= 1
        for s in g:
            if args['max_number'] == 0:
                break
            args['max_number'] -= 1
            args['output'].write(args['delimiter'])
            args['output'].write(s)
        if args['delimiter'] == '\n':
            args['output'].write('\n')   
```

`exrex -f paternfile.txt ""`
