### ISSUE TITLE
incorrect behavior in {n,m} Quantifier

### ISSUE THREAD

**Issue by zdilto** [asciimoo/exrex#58]
exrex will correctly Output quantifier result if following conditions are met:
"[9]{0,20}"   ---> {0-20,1-20}
"[9]{11,20}" ---> {11-???,20-???}

exrex will incorrectly Output quantifier result if following conditions are met:
"[9]{1,21}"     -----> m stops at 20
"[9]{9,30}"      --->   m stops at 28
"[9]{10,30}"    ---->  m stops at 29
"[9]{100,300}" --->  m stops at 119

UPDATE:
exrex will only iterate 20 times no matter the "m" quantifier is.

` exrex "[9]{10,40}"`

9999999999
99999999999
999999999999
9999999999999
99999999999999
999999999999999
9999999999999999
99999999999999999
999999999999999999
9999999999999999999
99999999999999999999
999999999999999999999
9999999999999999999999
99999999999999999999999
999999999999999999999999
9999999999999999999999999
99999999999999999999999999
999999999999999999999999999
9999999999999999999999999999
99999999999999999999999999999   ---> stopped only when "m" is 29 iterating 20 times

**Comment by sebix** [comment]
Citing the readme:
```
  -l N, --limit N       Max limit for range size - default is 20
```

**Comment by zdilto** [comment]
> Citing the readme:
> 
> ```
>   -l N, --limit N       Max limit for range size - default is 20
> ```

didn't notice it, thank you very much
