### ISSUE TITLE
Syntax error on import after initial install

### ISSUE THREAD

**Issue by krasmussen** [asciimoo/exrex#9]
# git clone https://github.com/asciimoo/exrex.git
Initialized empty Git repository in /tmp/exrex/.git/
remote: Counting objects: 353, done.
remote: Total 353 (delta 0), reused 0 (delta 0), pack-reused 353
Receiving objects: 100% (353/353), 391.81 KiB | 292 KiB/s, done.
Resolving deltas: 100% (165/165), done.
# cd exrex/
# python ./setup.py install
running install
running bdist_egg
running egg_info
creating exrex.egg-info
writing exrex.egg-info/PKG-INFO
writing top-level names to exrex.egg-info/top_level.txt
writing dependency_links to exrex.egg-info/dependency_links.txt
writing entry points to exrex.egg-info/entry_points.txt
writing manifest file 'exrex.egg-info/SOURCES.txt'
reading manifest file 'exrex.egg-info/SOURCES.txt'
writing manifest file 'exrex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying exrex.py -> build/lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib/exrex.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/exrex.py to exrex.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/exrex.py', 49, 33, 'REVERSE_CATEGORIES = {vv[1]:k for k,v\n'))

creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.6
copying and adjusting exrex.py -> build/scripts-2.6
changing mode of build/scripts-2.6/exrex.py from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.6/exrex.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/exrex.py to 755
copying exrex.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying exrex.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying exrex.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying exrex.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying exrex.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/exrex-0.9.3-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing exrex-0.9.3-py2.6.egg
creating /usr/lib/python2.6/site-packages/exrex-0.9.3-py2.6.egg
Extracting exrex-0.9.3-py2.6.egg to /usr/lib/python2.6/site-packages
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/exrex-0.9.3-py2.6.egg/exrex.py', 49, 33, 'REVERSE_CATEGORIES = {vv[1]:k for k,v\n'))

Adding exrex 0.9.3 to easy-install.pth file
Installing exrex.py script to /usr/bin
Installing exrex script to /usr/bin

Installed /usr/lib/python2.6/site-packages/exrex-0.9.3-py2.6.egg
Processing dependencies for exrex==0.9.3
Finished processing dependencies for exrex==0.9.3
# python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import exrex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "exrex.py", line 49
    REVERSE_CATEGORIES = {vv[1]:k for k,v
                                    ^
SyntaxError: invalid syntax
>>>

**Comment by asciimoo** [comment]
fixed @ 5874590de280db94d827ecca0d8d96408bea2a83
